format:
  indent: 4
  lineBreakBeforeEachArgument: true

rules:
  defaultAccessLevel:
    accessLevel: openOrPublic
    implicitInternal: true

  defaultMemberwiseInitializer:
    implicitInitializer: true
    implicitInternal: true
    ignoreClassesWithInheritance: true
