#if !canImport(ObjectiveC)
import XCTest

extension DefaultAccessLevelRuleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DefaultAccessLevelRuleTests = [
        ("testClass", testClass),
        ("testClassFinal", testClassFinal),
        ("testClassNested", testClassNested),
        ("testClassNotTriggered", testClassNotTriggered),
        ("testDescription", testDescription),
        ("testEnum", testEnum),
        ("testEnumNested", testEnumNested),
        ("testEnumNotTriggered", testEnumNotTriggered),
        ("testExtensionHasAccessLebel", testExtensionHasAccessLebel),
        ("testExtensionHasNoAccessLebel", testExtensionHasNoAccessLebel),
        ("testExtensionNestedHasAccessLebel", testExtensionNestedHasAccessLebel),
        ("testExtensionNestedHasNoAccessLebel", testExtensionNestedHasNoAccessLebel),
        ("testExtensionNotTriggered", testExtensionNotTriggered),
        ("testFilePrivate", testFilePrivate),
        ("testIgnore", testIgnore),
        ("testPrivate", testPrivate),
        ("testProtocol", testProtocol),
        ("testProtocolNotTriggered", testProtocolNotTriggered),
        ("testStruct", testStruct),
        ("testStructNested", testStructNested),
        ("testStructNotTriggered", testStructNotTriggered),
        ("testTopLevelFuction", testTopLevelFuction),
        ("testTopLevelVariable", testTopLevelVariable),
    ]
}

extension DefaultMemberwiseInitializerRuleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DefaultMemberwiseInitializerRuleTests = [
        ("testClass", testClass),
        ("testClassImplicitInitializer", testClassImplicitInitializer),
        ("testCustomFormat", testCustomFormat),
        ("testDescription", testDescription),
        ("testFilePrivate", testFilePrivate),
        ("testIgnore", testIgnore),
        ("testIgnoreClassesWithInheritance", testIgnoreClassesWithInheritance),
        ("testNotTriggered", testNotTriggered),
        ("testPrivate", testPrivate),
        ("testReserved", testReserved),
        ("testStruct", testStruct),
        ("testStructImplicitInitializer", testStructImplicitInitializer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DefaultAccessLevelRuleTests.__allTests__DefaultAccessLevelRuleTests),
        testCase(DefaultMemberwiseInitializerRuleTests.__allTests__DefaultMemberwiseInitializerRuleTests),
    ]
}
#endif
